#pragma once

#ifndef PROCESSNAMEW
#define PROCESSNAMEW L"ac_client.exe"
#endif // !PROCESSNAMEW

#ifndef DLLPATHW
#define DLLPATHW L"TestDll.dll"
#endif // !DLLPATHW

#define PRINT_PROCESSNAME L"Defined PRINT_PROCESSNAME: " PROCESSNAMEW
#define PRINT_ENTRY L"Defined: PRINT_ENTRY"
#define PRINT_MODULES L"Defined: PRINT_MODULES"
#undef PRINT_MODULES
#define PRINT_THREADS L"Defined: PRINT_THREADS"
#define PRINT_HANDLES L"Defined: PRINT_HANDLES"
#define PRINT_DLLPATH L"Defined PRINT_DLLPATH: " DLLPATHW
#define PRINT_SIMPLE_INJECTION L"Defined: PRINT_SIMPLE_INJECTION"