name: Snyk Security Scan

on:
  push:
    branches: [ master ]
  pull_request:

permissions:
  contents: read

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (if needed for JS/TS projects)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Snyk Code Scan
        uses: snyk/actions@v3
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: code test
