name: Snyk Code Scan

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Snyk Code
        uses: snyk/actions/snyk-code@v1
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
